feat:백업 1시간마다 하루지난백업 삭제

diff --git a/manifests/cronjobs/test-hybrid-db-backup.yaml b/manifests/cronjobs/test-hybrid-db-backup.yaml
--- a/manifests/cronjobs/test-hybrid-db-backup.yaml
+++ b/manifests/cronjobs/test-hybrid-db-backup.yaml
@@ -52,7 +52,19 @@ spec:
                 - -c
                 - |
                   export PGPASSWORD=$(cat /secrets/password)
-                  pg_dump -U "$PGUSER" -h test-hybrid-db-postgresql-ha-postgresql -d "$PGDATABASE" > /backup/backup-$(date +\%Y\%m\%d-\%H\%M\%S).sql
+                  FILENAME="/backup/backup-$(date +%Y%m%d-%H%M%S).sql"
+                  echo "[INFO] 시작: 백업을 $FILENAME 에 저장합니다."
+                  pg_dump -U "$PGUSER" -h test-hybrid-db-postgresql-ha-postgresql -d "$PGDATABASE" >"$FILENAME"
+                  if [ $? -eq 0 ]; then
+                    echo "[SUCCESS] 백업 완료: $FILENAME"
+                  else
+                    echo "[ERROR] 백업 실패: pg_dump 실패"
+                    exit 1
+                  fi
+                  # 오래된 백업 정리
+                  ls -1t /backup/*.sql | tail -n +26 | xargs -r rm --
+                  echo "[INFO] 정리 완료"
+
               volumeMounts:
                 - name: backup-vol
                   mountPath: /backup
